<main class = "container" id="experience">

	<section>

		<h1>Expérience</h1>


		<ul>
			<li>09/2016-02/17</li>
			<li>Technicien controle qualité Agro-Alimentaire</li>
			<li>ISHA – Institut Scientifique d'Hygiène et d'Analyse à Champlain</li>
			<li>Analyses de vitamines D, B1, B2, B8 et C dans des matrices agro alimentaires : yaourts, viande, biscuits... Rédaction d’un compte rendu d’analyse.</li>
		</ul>
		
		<ul>
			<li>11/2014-09/16</li>
			<li>Animatrice des activités periscolaires</li>
			<li>Mairie de Voisins-le-Bretonneux</li>
			<li>
				« Expériences de la chimie amusante » pour les  enfants de CP à CM2, création de supports visuels (Photoshop), 
				soutien scolaire en groupe, cours particuliers.
			</li>
		</ul>

		<ul>
			<li>03/2014-11/14</li>
			<li>Post-doctorant - CNRS</li>
			<li>OMC - Université de Rennes</li>
			<li>
				Synthèse et caractérisation des ligands taggués et des complexes de ruthénium.
				Collaboration entre les universités Rennes-Orsay-Caen.
			</li>
			<li><span>1 Publication scientifique.</span></li>
		</ul>

		<ul>
			<li>09/2013-01/14</li>
			<li>Technicien controle qualité pharmacéptique</li>
			<li>Laboratoire FARMACLAIR Groupe Fareva - Hérouville St-Clair</li>
			<li>
				Contrôle qualité des produits finis pharmaceutiques et cosmétiques.
				Dosages HPLC des principes actifs, aspect, viscosité, densité, pH.
				Rédaction d’un compte rendu d’analyse.
			</li>
		</ul>

		<ul>
			<li>05-06/2013</li>
			<li>Professeur remplaçant en mathematiques</li>
			<li>Collège St. Paul à Caen</li>
			<li>Enseignement au collège pour tous les niveaux, correction des copies, évaluation des progrès.</li>
		</ul>

		<ul>
			<li>2009-2012</li>
			<li><strong>Doctorat</strong> Chimie Organique Minérale, Industrielle</li>
			<li>LCMT - Université de Caen</li>
			<li>
				Définition de l’axe de recherche : analyse de contrainte de méthode (coût, temps, éco-compatibilité) proposition de stratégies de synthèse et des solutions d’optimisation.</li>
			<li>
				Etude de l’activité des complexes de fer dans des réactions d’oxydation et de la réduction afin d’aboutir à des substrats au potentiel bioactif. 
			</li>
			<li><span>3 Publications scientifiques</span>.</li>
		</ul>

		<ul>
			<li>01-06/2009</li>
			<li><strong>Ingenieur R&D</strong></li>
			<li>Institut Lavoisier - Versailles (Stage)</li>
			<li>Etude des complexes et des sels de fer comme activateurs pour des réactions de Friedel-Crafts.</li>
			<li>Réalisations des tests catalytiques: fonctionnalisation des composés aromatiques et hétéro aromatiques.</li>
		</ul>

		<ul>
			<li>04-07/2008</li>
			<li>Technicien R&D</li>
			<li>Institut Lavoisier - Versailles (Stage)</li>
			<li>Synthèse des dérivés de dianhydroexitols et leur application en tant que ligands pour des nouveaux complexes organométalliques.</li>
			<li>Valorisation des produits issus de la biomasse.</li>
		</ul>
		<ul>
			<li>06-07/2007</li>
			<li>Technicien R&D</li>
			<li>Institut Lavoisier - Versailles (Stage)</li>
			<li>Fonctionnalisation et étude de la réactivité des hétéro cycles azotés – benzofuroxans,
			composés potentiellement actifs contre la maladie d’Alzheimer.</li>
		</ul>

	</section>
</main>