<main class = "container" id="formation">
	<section>
					<h1>Formation</h1>

					<article>
						<h2>Continue</h2>
						<ul>
							<li>
								<strong>2017	DEVELOPPEUR LOGICIEL</strong> titre professionnel RNCP : 5927 à Paris «3W Academy».
							</li>
							<li>
								<strong>2016	« HPLC-UFLC appliquée aux Sciences du Vivant»</strong> Paris Diderot
							</li>
						</ul>
					</article>


					<article>
						<h2>Initiale</h2>
						<ul>
							<li>
								<strong>2012	DOCTORAT</strong> à l’université de Caen : Chimie Organique Minérale, Industrielle.
							</li>
							<li>
								<strong>2009	MASTER</strong> à l’université de Versailles : Réactivité moléculaire et matériaux.
							</li>
							<li>
								<strong>2007	LICENCE</strong> à l’université de Versailles : Chimie Organique.
							</li>
						</ul>
					</article>
	</section>


	<section>
		<h2>Publications et congrès</h2>

			<article id="publications">

				<h3>Publications</h3>
				<ul>
					<li>
						<a href="http://onlinelibrary.wiley.com/doi/10.1002/anie.201201360/abstract">Knölker's iron complex: an efficient in situ generated catalyst for reductive amination of alkyl aldehydes and amines.</a>
					</li>
					<li>
						Pagnoux-Ozherelyeva, A.; Pannetier, N.; Mbaye Diagne M.; Gaillard, S.; Renaud, J-L.* Angew. Chem. Int. Ed. 2012, 51, 4976.
					</li>
				</ul>

				<ul>
					<li>
						<a href="http://onlinelibrary.wiley.com/doi/10.1002/chem.201302432/abstract"> Bifunctional (cyclopentadienone)iron-tricarbonyl complexes: synthesis, computational studies and application in reductive amination.</a>
					</li>
					<li>
						Moulin, S.; Dentel, H.; Pagnoux-Ozherelyeva, A.; Gaillard, S.; Cavallo, L.; Lohier, J-F.; Renaud, J-L.  Chem. Eur. J. 2013, 19, 17881 – 17890.
					</li> 
				</ul>

				<ul>
					<li>
						<a href="http://www.sciencedirect.com/science/article/pii/S0022328X14004586">Microwave irradiation and flow chemistry for a straightforward synthesis of piano-stool iron complexes.</a>
					</li>
					<li>
						Pagnoux-Ozherelyeva, A. ; Bolien, D. ; Gaillard, S. ; Peudru, F. ;  Lohier, J. F. ;  Whitby, R. J. ;  Renaud, J-L. Journal of Organometallic Chemistry, 2014, 774, 35-42.
					</li>
				</ul>

				<ul>
					<li>
						<a href="http://onlinelibrary.wiley.com/doi/10.1002/ejoc.201403194/abstract">Immobilization of an Anthracene-Tagged Ruthenium Complex on a 2,4,7-Trinitrofluoren-9-one-Grafted Silica: Efficiency and Recyclability in Olefin Metathesis Reactions.</a>
					</li>
					<li>
						Nasrallah, H. ; Pagnoux, A. ; Didier, D. ; Magnier, C. ; Toupet, L ; Guillot, R. ; Crévisy, C. ; Mauduit, M. ; Schulz, E. European Journal of Organic Chemistry, 2014, 35, 7781–7787.
					</li>
					<li><a href="https://www.researchgate.net/scientific-contributions/74098890_Anastassiya_Pagnoux-Ozherelyeva">Anastassiya Pagnoux-Ozherelyeva's scientific contributions...</a></li>
				</ul>
			</article>

			<article>
			<h3>Congrès</h3>

			<ul>
				<li>2012	JEDNC à ROUEN : présentation orale</li>
			
				<li>2012	ANORCQ à CAEN : présentation orale, poster</li>
			
				<li>2011	SUMMER SCHOOL à NORWICH : présentation orale</li>
			
				<li>2011	Journées Nord-Ouest Européennes des Jeunes Chercheurs à CAEN : poster</li>
			
				<li>2010	SUMMER SCHOOL à SOUTHAMPTON</li>
			</ul>
		</article>
	</section>
</main>