<main class = "container" id="portfolio">
	<section>
		<h1>Portfolio</h1>
		
		<p>HTML 5, CSS 3, PHP5/7, JavaScript, MySQL</p>
		
		<figure>
			<a href="http://www.artisanat-menestrel.dx.am"><img src="img/artisanat.jpg"></a>
			<figcaption>Artisanat Tarbes</figcaption>
		</figure>

	</section>

	<section>
		<h2>Formation</h2>
			<ul>
				<li><strong>2017	DEVELOPPEUR LOGICIEL</strong> «3W Academy» Paris.</li>
				<li><strong>2012	DOCTORAT</strong> Chimie LCMT Caen.</li>
				<li><strong>2009	MASTER</strong> Chimie UVSQ Versailles.</li>
				<li><strong>2007	LICENCE</strong> Chimie UVSQ Versailles.</li>
			</ul>
	</section>


	<section>
		<h2>Compétences</h2>

		<article>
			<h3>Informatique</h3> 
			<ul>
				<li>
					<strong>Developpement-Integration WEB: HTML 5, CSS 3, JavaScript, PHP5/7, MySQL.</strong>
				</li>
				<li>
					Logiciels graphiques : Photoshop, Gimp, Corel IPE5 + tablette graphique.
				</li>
			</ul>
		</article>
	</section>

	<section>
			<h2>Compétences transverses</h2>
		<article>
			<h3>Informatique</h3>  
			<ul>
				<li>Logiciels d’analyses : Chromeleon 7.2, Topspin, Mnova NMR</li>
				<li>Base de données : Scifinder, Reaxis</li>
				<li>Editeur moléculaire : Chembiodraw</li>
			</ul>
		</article><!-- 
	
		--><article>
			<h3>Langues</h3>
			<ul>
				<li>Anglais, professionnel</li>
				<li>Russe, bilingue</li>
			</ul>
		</article><!--  
	
	--><article>
			<h3>Management</h3>
			<ul>
				<li>Pilotage de projet de recherche</li>
				<li>Collaborations scientifiques : Rennes-Caen-Orsay-Angleterre</li>
				<li>Management d’équipe de techniciens : 1 à 3 personnes</li>
				<li>Encadrement de stagiaires : Licence, Master, BTS</li>
				<li>Enseignement au collège : de 5-ème à 3-ème</li>
			</ul>
		</article><!--  

	--><article>
			<h3>Communication <br /> Veille scientifique</h3>
			<ul>
				<li>Recherche et analyse de l’information sur les progrès dans le domaine de la catalyse</li>
				<li>Utilisation de bases de données</li>
				<li>Rédaction de manuscrit de thèse</li>
				<li>Présentation des résultats et animation des réunions</li>
				<li>Participation au congrès</li>
				<li>4 publications, 3 communications et 2 posters</li>
			</ul>
		</article>
	</section>	
		
</main>