<!DOCTYPE html>
<html lang="fr">
	<head>
		<title>CV Anastassiya Pagnoux-<?=$page_title; ?></title>
		<meta name="description" content="Integrateur Développeur Web : HTML 5, CSS 3, JS (programmation orientée objet), PHP 5/7 (POO), MySQL. Formation initiale Doctorat en chimie-pilotage d’un projet de recherche." />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="css/normalize.css">
		<link rel="stylesheet" type="text/css" href="css/style.css">
	</head>
	<body>
		
		<header>
			<div>
				<p>Anastassiya Pagnoux</p>
			</div>

			<img src="img/logo1.png" alt="Integrateur Développeur Web" id="max" width = "300">
			<img src="img/logoMobil.png" alt="Integrateur Développeur Web" id="min">

			<nav>
				<ul class = "container">
					<li><a href="index.php">Portfolio</a></li><!--  
				--><li><a href="formation.php">Formation</a></li><!--  
				--><li><a href="experience.php">Experience</a></li><!--  
				--><li><a href="personalite.php">Personnalité</a></li>	
				</ul>
			</nav>
		</header>


			<?php include $template_name; ?>

		<footer>
		
			<h3><i class="fa fa-address-card"></i> Contacts</h3>
			<ul>
				<li>120 Avenue de la Division Leclerc</li>
				<li>92160 Antony</li>
				<li><i class="fa fa-mobile"></i> : 07 67 28 87 37 </li>
				<li><i class="fa fa-envelope"></i> : anastassiya.pagnoux@gmail.com</li>
				<li>32 ans, Permis B</li>
			</ul>
		</footer>
	</body>
</html>

